### PR TITLE
Fixes #1268

### LINKED ISSUE #1268: [Bug] image in readme would crash when default branch is not master
### Current behavior

image in readme would crash when default branch is not master

see project logo in [here](https://index.scala-lang.org/scalacenter/bloop)

### Expected Behavior

image in readme should display

### Extra comments

Should tune `Client.scala` rather hard code `master`

### Search terms

`master` or `blob` in `Client.scala`

### PR DESCRIPTION
**Pull request by mfirry**

### CODE REVIEW

File: modules/webclient/src/main/scala/scaladex/client/Client.scala [hunk 1]
```diff
@@ -84,6 +96,31 @@ object Client {
...
+        .flatMap { res =>
+          if (res.status == 200) {
+            res.text().toFuture.map(extractDefaultBranch)
+          } else { Future.successful("master") }
+        }
+        .map { res =>
+          val resJson = js.JSON.parse(res)
+          val branch = resJson.asInstanceOf[Repo].default_branch
+          fixImages(branch, organization, repository)
+        }
```
Comment (adpi2) [inline modules/webclient/src/main/scala/scaladex/client/Client.scala:116]: I deployed it to https://index-dev.scala-lang.org/scalacenter/bloop but it does not work.

It seems there is a problem here because it tries again to parse the default_branch to JSON.

```suggestion
        .map(branch => fixImages(branch, organization, repository))
```

Comment (mfirry) [reply modules/webclient/src/main/scala/scaladex/client/Client.scala:116]: Hmmm weird. I tried it locally.

Comment (mfirry) [reply modules/webclient/src/main/scala/scaladex/client/Client.scala:116]: Ah no. My bad. Let me see.
